### ISSUE TITLE
Ferrite bead part number

### ISSUE THREAD

**Issue by Merlin04** [shridattdudhat/ADS124S08#3]
I'm looking into building one of these boards (I'd buy it from your Tindie store but shipping would be $50), and I was able to find all of the parts on DigiKey except for the ferrite bead. There are [a lot of options](https://www.digikey.com/en/products/filter/ferrite-beads-and-chips/841?s=N4IgjCBcpgbFoDGUBmBDANgZwKYBoQB7KAbRAGYBOAJgBZ4BdAgBwBcoQBlVgJwEsAdgHMQAXwIBaaghDJIvAK74ipEAFYQBSiCYg2HMeJDTIZFDh79WOHQQ3Q9UMC2ZRqao-Ad8AJhwlgAAwQLOyQIJogrACezDbhaFjIoqJAA) and I don't know what parameters are needed. Could you provide the part number you are using?

**Comment by shridattdudhat** [comment]
Hi,

Sorry for the late reply. I know the shipping charges are too high. I am searching for cheap shipping options in my locality. Anyway, you can always build the board by yourself! 

For the ferrite bead, you can use https://www.digikey.com/en/products/detail/fair-rite-products-corp/2506036007Y3/8594266 
It has very low DC resistance 40mOhm and 60Ohm at 100Mhz.

The main function of the ferrite bead is to reduce switching noise and keep the analogue reading undisturbed from digital signals.

And If my work helps you to build your project and saves your time you can donate a minor amount on my [Paypal](https://www.paypal.com/paypalme/shridattdudhat). Your support will help me to make more awesome open source projects. Although It's not mandatory.

Thank you.

**Comment by Merlin04** [comment]
Ok, thank you so much!
